# Generated by Django 5.1.6 on 2025-04-06 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0003_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
    ]
