# Generated by Django 5.1.6 on 2025-04-25 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
