# Generated by Django 5.1.6 on 2025-04-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0007_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
